import turtle             
turtle.bgcolor("black")
turtle.pencolor("white")
turtle.fillcolor("green")
turtle.begin_fill()

turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)

turtle.end_fill()

turtle.fillcolor("orange")
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)

turtle.end_fill()
turtle.left(180)
turtle.forward(100)

turtle.fillcolor("red")
turtle.begin_fill()


turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()


turtle.penup()
turtle.goto(-250, 200)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(40)
turtle.end_fill()
turtle.penup()
turtle.goto(-250, 100)
turtle.pendown()
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.circle(40)
turtle.end_fill()
turtle.penup()

turtle.goto(-250, 0)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.circle(40)
turtle.end_fill()

turtle.done()